from .lenet import *
from .alexnet import *
#from .vgg import *
#from .resnet import *
from .squeezenet import *
from .squeezemobnet import *
from .mobilenet import *
from .mobilenetv2 import *
#from .shufflenet import *
