from .lenet import *
from .alexnet import *
from .vgg import *
from .resnet import *
from .squeezenet import *
from .squeezenetdsc import *
from .mobilenet import *
from .mobilenetv2 import *
from .shufflenet import *
